%% export_tables.m — Extract thermodynamic tables and write tables.h for C solver
% Run in Octave from the Shock-Tube directory:
%   octave --no-gui export_tables.m

fid = fopen('tables.h', 'w');
fprintf(fid, '/* Auto-generated by export_tables.m — do not edit */\n');
fprintf(fid, '#ifndef TABLES_H\n#define TABLES_H\n\n');

% Grid parameters (uniform grids) - matches the .m file grids exactly
% T: 150:2:400 = 126 points;  P: 100000:100000:20000000 = 200 points
fprintf(fid, '#define NT 126\n');
fprintf(fid, '#define NP 200\n');
fprintf(fid, '#define T_MIN 150.0\n');
fprintf(fid, '#define T_STEP 2.0\n');
fprintf(fid, '#define P_MIN 100000.0\n');
fprintf(fid, '#define P_STEP 100000.0\n\n');

% Build query points covering the full grid
T_grid = 150:2:400;           % 126 points
P_grid = 100000:100000:20000000;  % 200 points

% Call the persistent-variable functions to populate tables
dummy = methane_U(200, 1e6);
dummy = methane_Cv(200, 1e6);
dummy = methane_soundspeed(200, 1e6);

% Build full grids for interp2 queries
[PP, TT] = meshgrid(P_grid, T_grid);  % TT is 126x200, PP is 126x200

U_tab   = methane_U(TT, PP);
Cv_tab  = methane_Cv(TT, PP);
a_tab   = methane_soundspeed(TT, PP);

% Write each table
write_c_table(fid, 'U_table', U_tab, 126, 200);
write_c_table(fid, 'Cv_table', Cv_tab, 126, 200);
write_c_table(fid, 'a_table', a_tab, 126, 200);

fprintf(fid, '#endif /* TABLES_H */\n');
fclose(fid);
fprintf('tables.h written successfully (%d x %d tables)\n', 126, 200);
